---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Display parsed parameters
      debug:
        msg: 
          - "api_url: {{ api_url }}"
          - "console_url: {{ console_url }}"
          - "username: {{ username }}"
          - "password: {{ password }}"

    - name: Parse JSON output to variables
      set_stats:
        data:
          api_url: "{{ api_url }}"
          console_url: "{{ console_url }}"
          username: "{{ username }}"
          password: "{{ password }}"

    - name: Notify to Teams
      uri:
        url: "https://prod-11.southeastasia.logic.azure.com:443/workflows/9717b9afb76c4e04ba52d87cce1135aa/trig[…]&sig=OkiaRgNztIRrnrOMIjQfaT43Vz9dwYnfbpyrYl7Sy3E"
        method: POST
        body_format: "json"
        body:
          title: "[STEP2] ROSAクラスタ作成完了"
          message: "ROSAクラスタ作成が完了しました。"
          api_url: "{{ api_url }}"
          console_url: "{{ console_url }}"
          username: "{{ username }}"
          password: "{{ password }}"
      register: result