---
- name: Setup rosa cluster from a ansible playbook.
  hosts: all
  gather_facts: false
  tasks:
    - name: Execute script and parse JSON output
      command: echo '{"param1":"value1","param2":"value2","param3":"value3"}'
      register: result

    - name: Parse JSON output to variables2
      set_stats:
        data:
          param1: "1"
          param2: "2"
          param3: "3"