---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: debug
      ansible.builtin.debug:
        msg:
          api_url: "{{ api_url }}"
          api_token: "{{ api_token }}"

    - name: Parse JSON output to variables
      set_stats:
        data:
          api_url: "{{ api_url }}"
          api_token: "{{ api_token }}"

    - name: Create a sample namespace
      kubernetes.core.k8s:
        name: sample-namespace
        api_version: v1
        host: "{{ api_url }}"
        api_key: "{{ api_token }}"
        kind: Namespace
        state: present

    - name: Notify to Teams
      uri:
        url: "https://prod-63.southeastasia.logic.azure.com:443/workflows/5fccc786ff304019a64ec9949c6a0d95/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=LChi9A1c3aexboQI_yjMekJTdSRZR2JM758fM6oKcZQ"
        method: POST
        body_format: "json"
        status_code: 202
        body:
          message: "message"
      register: result