---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Display parsed parameters
      debug:
        msg: 
          - "Param1: {{ param1 }}"
          - "Param2: {{ param2 }}"
          - "Param3: {{ param3 }}"