---
- name: ROSA Cluster Create
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute script
      command: /home/runner/rosa.sh
      register: s_result

    - name: Parse JSON output
      set_fact:
        result: "{{ s_result.stdout_lines[-1] | from_json }}"

    - name: debug
      ansible.builtin.debug:
        var: result

    - name: Parse JSON output to variables
      set_stats:
        data:
          api_url: "{{ result.api_url }}"
          api_token: "{{ result.api_token}}"

    - name: Notify to Teams
      uri:
        url: "https://prod-40.southeastasia.logic.azure.com:443/workflows/9b3bdcce3cc04f89868857c7714b496d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=D_RqlwqoFNoYQaLWyLQ5ohvHjTy2kByGWYJLGl8zZ74"
        method: POST
        body_format: "json"
        status_code: 202
        body:
          api_url: "{{ result.api_url }}"
          console_url: "{{ result.console_url }}"
          username: "{{ result.username }}"
          password: "{{ result.password }}"
          display_name: "{{ result.display_name }}"
          region: "{{ result.region }}"
          openshift_version: "{{ result.openshift_version }}"
          end_of_life_timestamp: "{{ result.end_of_life_timestamp }}"
      register: o_result

