- name: Notification
  hosts: localhost
  tasks:
    - name: debug
      ansible.builtin.debug:
        msg:
          api_url: "{{ api_url }}"
          api_token: "{{ api_token }}"

    - name: Get cluster version
      kubernetes.core.k8s_info:
        api_version: v1
        kind: ClusterVersion
        name: version
        host: "{{ api_url }}"
        api_key: "{{ api_token }}"
      register: cluster_version_info

    - name: Assert cluster version
      ansible.builtin.assert:
        that:
          - cluster_version_info.resources[0].status.history[0].version == '4.15.37'
      failed_when: false
      register: result1

    - name: Get all nodes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Node
      register: node_info

    - name: Assert the number of workernode
      ansible.builtin.assert:
        that:
          - node_info.resources | length == 2
      register: result2

    - name: Notify to Teams
      uri:
        url: "https://prod-54.southeastasia.logic.azure.com:443/workflows/0734ebc58877417bbd89a4d96e6a5cc2/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=In2970iNhm0oLRIp5qA8jF4iVl19qjmRJktdtlSm1hY"
        method: POST
        status_code: 202
        body_format: "json"
        body:
          check1: "{{ result1.msg }}"
          check2: "{{ result2.msg }}"
      register: result