---
- name: Setup rosa cluster from a ansible playbook.
  hosts: all
  gather_facts: false
  tasks:
    - name: Execute script and parse JSON output
      command: echo '{"param1":"value1","param2":"value2","param3":"value3"}'
      register: result

    - name: Parse JSON output to variables
      set_fact:
        parsed_results: "{{ result.stdout | from_json }}"
        cacheable: true

    - name: Display parsed parameters
      debug:
        msg: 
          - "Param1: {{ parsed_results.param1 }}"
          - "Param2: {{ parsed_results.param2 }}"
          - "Param3: {{ parsed_results.param3 }}"
