- name: Error Notification
  hosts: localhost
  tasks:
    - name: Notify to Teams
      uri:
        url: "https://prod-04.southeastasia.logic.azure.com:443/workflows/0fbe2ad8833c4b3cbb0e504481742470/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=nUSzctmwZtrxIn5IQag4jhOJw4w0L_ExKLU4pkTi4dg"
        method: POST
        body_format: "json"
        body:
          code: "{{ code }}"
          message: "{{ message }}"
      register: result

    - name: debug
      ansible.builtin.debug:
        var: result
